@extends('layouts.home')

@section('content')
    <h2>Hello</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi consectetur tortor sapien, quis tincidunt risus sodales at. Integer sit amet lorem convallis, elementum augue sed, ornare sem. Phasellus vulputate augue vel lectus molestie, vitae accumsan dui varius. Vestibulum gravida commodo posuere. Etiam ut erat non felis dictum condimentum. Sed tempus mi non ultrices sodales. Proin urna risus, aliquam in sapien sed, faucibus imperdiet purus. Phasellus pretium, lacus ut suscipit porta, metus neque gravida purus, id auctor quam libero vitae urna. Duis arcu mauris, dapibus at tristique quis, rutrum eget erat. Maecenas posuere non turpis quis consequat. Curabitur sed faucibus erat. Nunc tincidunt egestas tortor, id aliquam metus euismod quis. Morbi luctus, lectus non sodales dapibus, diam magna mollis elit, quis vulputate lacus urna in lorem. Aliquam metus mauris, efficitur eu malesuada id, rutrum eu felis.

        Curabitur eu tincidunt justo, dignissim condimentum diam. Quisque leo tortor, venenatis ut velit ut, pharetra condimentum augue. Cras urna lectus, blandit eu justo aliquam, efficitur tempor ante. Ut in auctor purus, sit amet pretium libero. In convallis tempor fermentum. Vestibulum porttitor justo sapien, eu dignissim tortor tincidunt nec. Duis nec metus aliquet, varius purus eu, tristique nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus et risus dignissim, posuere purus a, luctus ligula. Quisque efficitur laoreet erat non malesuada. Fusce ultricies hendrerit augue in pulvinar. Proin malesuada, nisl nec ultrices viverra, nibh ligula consectetur ipsum, nec ornare sapien massa eu enim. Suspendisse potenti.

        Integer id velit faucibus neque ultrices elementum eget vitae lectus. Integer eget purus mi. In hac habitasse platea dictumst. Duis molestie vitae urna vitae posuere. Nam eleifend ex in nisl rhoncus laoreet. Donec gravida consequat tortor nec tincidunt. Nunc ac dapibus nisl. Nam ut neque in justo tincidunt elementum.

        Donec sit amet rhoncus neque, bibendum facilisis nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque et dui at orci molestie rutrum. Etiam dictum tellus sit amet imperdiet gravida. Ut convallis sapien vel nulla tincidunt ultrices. Proin sed mi vel ligula fermentum euismod quis a turpis. Suspendisse potenti. Phasellus tempor cursus tincidunt. Suspendisse orci mi, consequat ac ullamcorper ut, accumsan quis nisi. Donec rhoncus, nibh at efficitur laoreet, turpis est facilisis orci, id pretium eros turpis pellentesque tortor. Proin at egestas turpis, in posuere libero.

        Maecenas suscipit porta dui sed porttitor. Etiam rutrum sem nisl, ac semper massa porta gravida. Nunc vestibulum posuere ipsum vitae commodo. Aenean porttitor pretium enim at vulputate. In feugiat odio lacus, in feugiat ipsum lobortis id. Donec venenatis pellentesque lacus, non cursus tortor tempus et. Aliquam tortor mi, porta non interdum et, vestibulum quis nisi. Vestibulum porta lorem quis vestibulum pharetra. Mauris ut enim sed quam commodo dictum. Sed ut leo feugiat, dictum mauris vel, consectetur augue. In pellentesque turpis a scelerisque volutpat. Maecenas sed semper est, id pulvinar sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin eu pharetra mauris, vel consequat odio. Maecenas a volutpat libero, eu suscipit sem. Suspendisse rutrum massa nec mi blandit, ac consequat ipsum faucibus.
    </p>
@endsection
